---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install --prefix ./frontend
  - npm install --prefix ./backend

script:
  - npm test --prefix ./frontend
  - npm test --prefix ./backend
