---
language: node_js
node_js:
  - "8"

sudo: required

dist: trusty

addons:
  chrome: stable


cache:
  yarn: true

services:
    - docker

before_install:
  - if [ "$DIR" = "backend" ]; then wget https://raw.githubusercontent.com/eficode/wait-for/master/wait-for; fi
  - if [ "$DIR" = "backend" ]; then sudo service postgresql stop; fi
  - if [ "$DIR" = "backend" ]; then while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done; fi
  - if [ "$DIR" = "backend" ];
      then
        (docker run -d -p 4389:389
        -v $PWD/tools/docker/ldap/ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
        --env LDAP_ORGANISATION=adsy
        --env LDAP_DOMAIN=adsy-ext.becs.adfinis-sygroup.ch
        --env LDAP_ADMIN_PASSWORD=123qwe
        --env LDAP_OPENLDAP_UID=1000
        --env LDAP_OPENLDAP_GID=1000
        --env LDAP_TLS=false
        --env LDAP_BASE_DN=dc=adsy-ext,dc=becs,dc=adfinis-sygroup,dc=ch
        osixia/openldap
        --copy-service
        --loglevel debug);
      fi
  - if [ "$DIR" = "backend" ]; then bash wait-for localhost:4389; fi
  - if [ "$DIR" = "backend" ];
      then
        (docker run -d -p 5432:5432
        -v $PWD/tools/docker/postgres/setup/:/docker-entrypoint-initdb.d/
        -v $PWD/tools/docker/postgres/timed-test-data.sql:/tmp/timed-test-data.sql
        --env POSTGRES_USER=test
        --env POSTGRES_PASSWORD=test
        --env POSTGRES_DB=customercenter
        postgres)
      fi
  - if [ "$DIR" = "backend" ]; then bash wait-for localhost:5432; fi
  - if [ "$DIR" = "backend" ]; then docker run -d -p 6379:6379 redis; fi
  - if [ "$DIR" = "backend" ]; then bash wait-for localhost:6379; fi
  - if [ "$DIR" = "backend" ]; then docker run -d -p 1080:1080 schickling/mailcatcher; fi
  - if [ "$DIR" = "backend" ]; then bash wait-for localhost:1080; fi

install:
  - (cd $DIR; yarn)

script:
  - if [ "$DIR" = "backend" ]; then make -C backend/ test-migrations; fi
  - (cd $DIR; yarn test)

env:
  - JOBS=2 DIR=frontend
  - JOBS=2 DIR=backend
