---
language: node_js
node_js:
  - "6"

sudo: false

dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false

install:
  - npm install -g bower
  - npm install --prefix ./frontend
  - npm install --prefix ./backend
  - cd ./frontend && bower install && cd ..

script:
  - npm test --prefix ./frontend
  - npm test --prefix ./backend
