version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./tools/docker/nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    ports:
      - "8888:80"

  backend:
    image: node:10
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - ./tools/docker/rt4/var/rt4:/var/rt4/rt4
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - DEBUG=app:*
    ports:
      - "3000:3000"
    command: yarn watch

  # frontend:
  #   image: node:8
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/tmp
  #     - /usr/src/app/dist
  #   ports:
  #     - "7020:7020"
  #   command: yarn start-proxy

  redis:
    image: redis
    ports:
      - "6379:6379"

  ldap:
    image: osixia/openldap
    ports:
      - "4389:389"
    volumes:
      - ./tools/docker/ldap/ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    environment:
      - LDAP_ORGANISATION=adsy
      - LDAP_DOMAIN=adsy-ext.becs.adfinis-sygroup.ch
      - LDAP_ADMIN_PASSWORD=123qwe
      - LDAP_OPENLDAP_UID=1000
      - LDAP_OPENLDAP_GID=1000
      - LDAP_TLS=false
      - LDAP_BASE_DN=dc=adsy-ext,dc=becs,dc=adfinis-sygroup,dc=ch
    command: ["--copy-service", "--loglevel", "debug"]

  ldapadmin:
    image: osixia/phpldapadmin
    volumes:
        - ./tools/docker/ldapadmin/config.php:/container/service/phpldapadmin/assets/config/config.php
    ports:
      - "6443:80"
    environment:
      #- PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_CLIENT_TLS=false
    command: ['--copy-service']

  postgres:
    image: postgres
    volumes:
      - ./tools/docker/postgres/setup/:/docker-entrypoint-initdb.d/
      - ./tools/docker/postgres/timed-test-data.sql:/tmp/timed-test-data.sql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=customercenter
    ports:
      - "5432:5432"

  pgadmin:
    image: fenglc/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:5050"
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASSWORD=admin

  # User older version because the newer version does not work
  # vault:
  #   image: vault:0.9.0
  #   environment:
  #     - VAULT_DEV_ROOT_TOKEN_ID=myroot
  #     - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
  #   ports:
  #     - "8200:8200"

  timedbackend:
    image: adfinissygroup/timed-backend:v1.0.0
    ports:
      - '8000:80'
    depends_on:
      - postgres
    environment:
      - DJANGO_OIDC_CREATE_USER=True
      - DJANGO_OIDC_CHECK_INTROSPECT=True
      - DJANGO_OIDC_CLIENT_ID=timed-confidential
      - DJANGO_OIDC_CLIENT_SECRET=802635ae-2395-4419-b15b-b09dc838db14
      - DJANGO_OIDC_DEFAULT_BASE_URL=http://keycloak:8080/auth/realms/master/protocol/openid-connect
      - DJANGO_DATABASE_HOST=postgres
      - DJANGO_DATABASE_USER=test
      - DJANGO_DATABASE_PASSWORD=test
      - DJANGO_DATABASE_NAME=timed
      - ENV=docker
      - STATIC_ROOT=/var/www/static
    command: /bin/sh -c "wait-for-it.sh -t 60 postgres:5432 -- ./manage.py migrate && uwsgi"

  # gitlab:
  #   image: 'gitlab/gitlab-ce:latest'
  #   logging:
  #     driver: "none"
  #   ports:
  #     - '5080:80'
  #     - '5443:443'
  #     - '5022:22'

  # gitlab-runner:
  #   image: 'gitlab/gitlab-runner:latest'
  #   depends_on:
  #     - gitlab

  # mailcatcher:
  #   image: schickling/mailcatcher
  #   ports:
  #     - '1080:1080'

  # rt:
  #   build: ../rt-rest-api.src
  #   ports:
  #     - '8001:80'
  #   volumes:
  #     - ../rt-rest-api.src:/app
  #   environment:
  #     - DJANGO_DB_USER=${DJANGO_DB_USER}
  #     - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
  #     - DJANGO_DB_HOST=${DJANGO_DB_HOST}
  #     - STATIC_ROOT=/var/www/static
  #     - DJANGO_AUTH_LDAP_SERVER_URI=ldap://ldap:389

  keycloak:
    image: jboss/keycloak:10.0.2
    depends_on:
      - postgres
    volumes:
      - ./tools/docker/keycloak/:/etc/keycloak/
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_DATABASE=customercenter
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8080:8080"
    command: # http://www.keycloak.org/docs/3.3/server_admin/topics/export-import.html
      [
        "-Dkeycloak.migration.action=import",
        "-Dkeycloak.migration.provider=singleFile",
        "-Dkeycloak.migration.file=/etc/keycloak/config.json",
        "-b",
        "0.0.0.0",
      ]
