web1:
  extends:
    file: ./tools/docker/compose.yml
    service: web
  volumes:
    - ./tools/docker/nginx/nginx-dev.conf:/etc/nginx/nginx.conf
  image: nginx
  links:
    - backenddev1
    - backenddev2
    - backenddev3
    - frontenddev1
  ports:
    - "8080:80"

backenddev1:
  extends:
    file: ./tools/docker/compose.yml
    service: backend-dev
  links:
    - redis1
    - postgres1
    - ucs1
    - redmine1
    - rt1
  environment:
    - TEST=1

backenddev2:
  extends:
    file: ./tools/docker/compose.yml
    service: backend-dev
  links:
    - redis1
    - postgres1
    - ucs1
    - redmine1
    - rt1
  environment:
    - TEST=2

backenddev3:
  extends:
    file: ./tools/docker/compose.yml
    service: backend-dev
  links:
    - redis1
    - postgres1
    - ucs1
    - redmine1
    - rt1
  environment:
    - TEST=3

frontenddev1:
  extends:
    file: ./tools/docker/compose.yml
    service: frontend-dev
  volumes:
    - ./frontend:/usr/src/app
  ports:
    - "35729:35729"

redis1:
  extends:
    file: ./tools/docker/compose.yml
    service: redis

ucs1:
  extends:
    file: ./tools/docker/compose.yml
    service: ucs
  hostname: acme-inc
  environment:
    - rootpwd=univention
  ports:
    - "8083:80"

postgres1:
  extends:
    file: ./tools/docker/compose.yml
    service: postgres
  environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test

redmine1:
  image: sameersbn/redmine:latest
  links:
    - redmine1postgres
  environment:
    - DB_TYPE=postgres
    - DB_HOST=redmine1postgres
    - DB_NAME=redmine
    - DB_USER=test
    - DB_PASS=test
  ports:
    - "8081:80"

redmine1postgres:
  image: postgres
  environment:
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test

rt1:
  image: jbfink/rt:latest
  command: /opt/rt4/sbin/rt-server
  volumes:
    - ./tools/docker/rt4/etc/RT_Config.pm:/opt/rt4/etc/RT_Config.pm
    - ./tools/docker/rt4/etc/RT_SiteConfig.pm:/opt/rt4/etc/RT_SiteConfig.pm
    - ./tools/docker/rt4/var/rt4:/opt/rt4/var/rt4
  ports:
    - "8082:8082"
