name: Test (Frontend)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true
  NODE_VERSION: 18

jobs:
  lint:
    name: Lint (Frontend)
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        target: [js, hbs]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn --cwd=frontend install

      - name: Lint ${{ matrix.target }}
        run: yarn --cwd=frontend lint:${{ matrix.target }}

  test:
    name: Tests (Frontend)
    needs: [lint]
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn --cwd=frontend install

      - name: Run tests
        run: yarn --cwd=frontend test
